package com.briup.cms.dao;

import com.briup.cms.bean.Cms_coment;
import com.briup.cms.bean.Cms_comentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Cms_comentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    long countByExample(Cms_comentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int deleteByExample(Cms_comentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int insert(Cms_coment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int insertSelective(Cms_coment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    List<Cms_coment> selectByExampleWithBLOBs(Cms_comentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    List<Cms_coment> selectByExample(Cms_comentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    Cms_coment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cms_coment record, @Param("example") Cms_comentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Cms_coment record, @Param("example") Cms_comentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByExample(@Param("record") Cms_coment record, @Param("example") Cms_comentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByPrimaryKeySelective(Cms_coment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Cms_coment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coment
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByPrimaryKey(Cms_coment record);
}