package com.briup.cms.dao;

import com.briup.cms.bean.Cms_category;
import com.briup.cms.bean.Cms_categoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Cms_categoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    long countByExample(Cms_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int deleteByExample(Cms_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int insert(Cms_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int insertSelective(Cms_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    List<Cms_category> selectByExample(Cms_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    Cms_category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cms_category record, @Param("example") Cms_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByExample(@Param("record") Cms_category record, @Param("example") Cms_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByPrimaryKeySelective(Cms_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Wed Nov 13 09:31:53 CST 2019
     */
    int updateByPrimaryKey(Cms_category record);
}